// SPDX-FileCopyrightText: 2023 SAP SE
//
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of FEDEM - https://openfedem.org
////////////////////////////////////////////////////////////////////////////////

#ifndef FFU_DIALOG_TYPE_H
#define FFU_DIALOG_TYPE_H

namespace FFuDialog
{
  enum DialogType {
    INFO,
    ERROR,
    WARNING,
    QUESTION,
    FT_LOGO,
    SAP_LOGO
  };
}

#endif
