// SPDX-FileCopyrightText: 2023 SAP SE
//
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of FEDEM - https://openfedem.org
////////////////////////////////////////////////////////////////////////////////

#pragma once

#define NOGDI
#define WIN32_LEAN_AND_MEAN // excludes rarely-used stuff from Windows headers
#define _WIN32_WINNT _WIN32_WINNT_MAXVER // to avoid compiler warning
#define _AFXDLL
#define _ATL_CSTRING_EXPLICIT_CONSTRUCTORS // some CString constructors will be explicit
#define _AFX_ALL_WARNINGS // turns off MFC's hiding of some common and often safely ignored warning messages

#include <afxwin.h>   // MFC core and standard components
#include <afxext.h>   // MFC extensions
#include <afxdisp.h>  // MFC Automation classes

#include "CaMain.h"   // Generated by MIDL
