// SPDX-FileCopyrightText: 2023 SAP SE
//
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of FEDEM - https://openfedem.org
////////////////////////////////////////////////////////////////////////////////

#include "CaCommonHeaders.h"
#include "CaMain_i.c" // Generated by MIDL
#include "CaApplication.h" // COM Application
#include "FFaLib/FFaCmdLineArg/FFaCmdLineArg.H"


bool CaInit()
{
  // Initialize MFC and print and error on failure
  AFX_MANAGE_STATE(AfxGetAppModuleState());
  HINSTANCE hInstance = GetModuleHandle(NULL);
  if (!AfxWinInit(hInstance, NULL, "", 0))
    return false;

  // Initialize OLE libraries
  if (!AfxOleInit())
    return false;

  ::OleInitialize(NULL);

  // Set module state
  AFX_MODULE_STATE* pModuleState = AfxGetModuleState();
  pModuleState->m_lpszCurrentAppName = "Fedem"; // Long readable name
  pModuleState->m_bDLL = 0; // EXE

  // Register all
  COleTemplateServer::RegisterAll();

  // Create and register active object
  CaApplication* pCaApplication = (CaApplication*)CaApplication::CreateObject();
  if (pCaApplication != NULL) {
    IApplication* pIApplication = NULL;
    LPDISPATCH pDisp = pCaApplication->GetIDispatch(false);
    DWORD tmp = 0;
    GUID guid = IID_IApplication;
    DWORD pid = GetCurrentProcessId();
    guid.Data4[4] = HIBYTE(HIWORD(pid));
    guid.Data4[5] = LOBYTE(HIWORD(pid));
    guid.Data4[6] = HIBYTE(LOWORD(pid));
    guid.Data4[7] = LOBYTE(LOWORD(pid));
    RegisterActiveObject((IUnknown*)pDisp, guid, 0, &tmp);
  }

  bool bRunEmbedded, bRunAutomated, bRegister, bUnregister;
  FFaCmdLineArg::instance()->getValue("Embedding", bRunEmbedded);
  FFaCmdLineArg::instance()->getValue("Automation", bRunAutomated);
  FFaCmdLineArg::instance()->getValue("regserver", bRegister);
  FFaCmdLineArg::instance()->getValue("unregister", bUnregister);
  if (bRunEmbedded || bRunAutomated)
    return true; // TODO: Hide all GUI stuff
  else if (bUnregister) {
    AfxOleUnregisterTypeLib(LIBID_FEDEM);
    return false; // Needed by the build system
  }

  // Update registry
  COleObjectFactory::UpdateRegistryAll();
  AfxOleRegisterTypeLib(hInstance,LIBID_FEDEM);

  return !bRegister;
}
