// SPDX-FileCopyrightText: 2023 SAP SE
//
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of FEDEM - https://openfedem.org
////////////////////////////////////////////////////////////////////////////////

#ifndef FUI_ICON_PIXMAPS_H
#define FUI_ICON_PIXMAPS_H

#include "vpmDB/Icons/FmIconPixmaps.H"

extern const char* IVSnapshot_xpm[];
extern const char* ManageSolve_xpm[];
extern const char* RGBSnapshot_xpm[];
extern const char* StopProcessing_xpm[];
extern const char* additionalSolverOptions_xpm[];
extern const char* animPause_xpm[];
extern const char* animPlayRwd_xpm[];
extern const char* animPlay_xpm[];
extern const char* animStepFwd_xpm[];
extern const char* animStepRwd_xpm[];
extern const char* animStop_xpm[];
extern const char* animToFirst_xpm[];
extern const char* animToLast_xpm[];
extern const char* animationControl_xpm[];
extern const char* animationExit_xpm[];
extern const char* animationLoad_xpm[];
extern const char* animation_xpm[];
extern const char* startGuideIcon_xpm[];
extern const char* appearance_xpm[];
extern const char* attach_xpm[];
extern const char* backwardSelect_xpm[];
extern const char* browseRDB_xpm[];
extern const char* cascade_xpm[];
extern const char* createGenericPart_xpm[];
extern const char* ctrlAddPoint_xpm[];
extern const char* ctrlGrid_xpm[];
extern const char* ctrlRemovePoint_xpm[];
extern const char* ctrlRotate_xpm[];
extern const char* ctrlSystem_xpm[];
extern const char* curve_xpm[];
extern const char* curvePlotZoomWindow_xpm[];
extern const char* curvePlotZoomWindowAS_xpm[];
extern const char* deleteDutyCycle_xpm[];
extern const char* deleteModes_xpm[];
extern const char* deleteRosetteResults_xpm[];
extern const char* deleteStrainCoat_xpm[];
extern const char* deleteStressResults_xpm[];
extern const char* detach_xpm[];
extern const char* duplicateLink_xpm[];
extern const char* edit_xpm[];
extern const char* eraseAllRes_xpm[];
extern const char* eraseSimuleRes_xpm[];
extern const char* eraseSimuleResEvents_xpm[];
extern const char* eraseStickers_xpm[];
extern const char* erase_xpm[];
extern const char* extCtrlSys_xpm[];
extern const char* flatColor_xpm[];
extern const char* force_xpm[];
extern const char* forwardSelect_xpm[];
extern const char* getFELink_xpm[];
extern const char* graph_xpm[];
extern const char* graphGroup_xpm[];
extern const char* infoList_xpm[];
extern const char* isometricView_xpm[];
extern const char* lineView_xpm[];
extern const char* lineViewObj_xpm[];
extern const char* linkRamSettings_xpm[];
extern const char* look_xpm[];
extern const char* manageSolveModes_xpm[];
extern const char* manageSolveRosette_xpm[];
extern const char* manageSolveStrainCoat_xpm[];
extern const char* manageSolveStress_xpm[];
extern const char* manageSolveDutyCycle_xpm[];
extern const char* matrixfile_xpm[];
extern const char* modelManager_xpm[];
extern const char* modesResList_xpm[];
extern const char* mouseArrow_xpm[];
extern const char* mouseMedium_xpm[];
extern const char* mouseSmall_xpm[];
extern const char* new_xpm[];
extern const char* objectBrowser_xpm[];
extern const char* openMechModeller_xpm[];
extern const char* open_xpm[];
extern const char* panDown_xpm[];
extern const char* panLeft_xpm[];
extern const char* panRight_xpm[];
extern const char* panUp_xpm[];
extern const char* pan_xpm[];
extern const char* paralellView_xpm[];
extern const char* pdf_xpm[];
extern const char* perspectiveView_xpm[];
extern const char* pointToPointMove_xpm[];
extern const char* prepareForBatch_xpm[];
extern const char* print_xpm[];
extern const char* propertyEditor_xpm[];
extern const char* reduceLinks_xpm[];
extern const char* reducerFail_xpm[];
extern const char* reducerNotRun_xpm[];
extern const char* reducerOK_xpm[];
extern const char* refreshRDB_xpm[];
extern const char* results_disabled_xpm[];
extern const char* results_enabled_xpm[];
extern const char* save_xpm[];
extern const char* showTopFaces_xpm[];
extern const char* solidView_xpm[];
extern const char* solidViewNoEdge_xpm[];
extern const char* solidViewObj_xpm[];
extern const char* solveAll_xpm[];
extern const char* solveAllEvents_xpm[];
extern const char* solveModes_xpm[];
extern const char* solveRosette_xpm[];
extern const char* solveStrainCoat_xpm[];
extern const char* solveDutyCycle_xpm[];
extern const char* solveStress_xpm[];
extern const char* solve_xpm[];
extern const char* showRDBselector_xpm[];
extern const char* spider_xpm[];
extern const char* spider_gen_xpm[];
extern const char* spider_gen_rbe2_xpm[];
extern const char* spider_gen_rbe3_xpm[];
extern const char* spider_geom_xpm[];
extern const char* spider_geom_rbe2_xpm[];
extern const char* spider_geom_rbe3_xpm[];
extern const char* splitBeam_xpm[];
extern const char* summaryfile_xpm[];
extern const char* symbolSize_xpm[];
extern const char* textfile_xpm[];
extern const char* tabs_xpm[];
extern const char* tile_xpm[];
extern const char* torque_xpm[];
extern const char* undo_xpm[];
extern const char* redo_xpm[];
extern const char* viewFilter_xpm[];
extern const char* View_XYnZpY_xpm[];
extern const char* View_XYpZpY_xpm[];
extern const char* View_XZnYpZ_xpm[];
extern const char* View_XZpYpZ_xpm[];
extern const char* View_YZnXpZ_xpm[];
extern const char* View_YZpXpZ_xpm[];
extern const char* vtf_xpm[];

extern const char* info_xpm[];
extern const char* help_xpm[];
extern const char* beamstringPairDef_xpm[];
extern const char* windAirEnv_xpm[];

extern const char* treeObjects_xpm[];
extern const char* treeObjectsSel_xpm[];
extern const char* treeResults_xpm[];

extern const char* eventDef_xpm[];
extern const char* objectInfo_xpm[];
extern const char* measureDistance_xpm[];
extern const char* measureAngle_xpm[];

extern const char* zoom_xpm[];
extern const char* zoomAll_xpm[];
extern const char* zoomTo_xpm[];
extern const char* zoomIn_xpm[];
extern const char* zoomOut_xpm[];

#endif
