// SPDX-FileCopyrightText: 2023 SAP SE
//
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of FEDEM - https://openfedem.org
////////////////////////////////////////////////////////////////////////////////

#ifndef FUI_ICON_PIXMAPS_MAIN_H
#define FUI_ICON_PIXMAPS_MAIN_H

#include "vpmDB/Icons/FmIconPixmapsMain.H"

// File icons
#include "new.xpm"
#include "open.xpm"
#include "save.xpm"
#include "print.xpm"
#include "edit.xpm"

// Windows icons
#include "tile.xpm"
#include "tabs.xpm"
#include "cascade.xpm"

// File browser icons
#include "results_disabled_xpm.xpm"
#include "results_enabled_xpm.xpm"
#include "matrixfile_xpm.xpm"
#include "textfile_xpm.xpm"
#include "summaryfile_xpm.xpm"
#include "reducerFail_xpm.xpm"
#include "reducerNotRun_xpm.xpm"
#include "reducerOK_xpm.xpm"

// Other useful icons
#include "look.xpm"
#include "mouseArrow.xpm"
#include "mouseSmall.xpm"
#include "mouseMedium.xpm"
#include "undo.xpm"
#include "redo.xpm"
#include "objectBrowser.xpm"
#include "startGuideIcon.xpm"
#include "measureDistance.xpm"
#include "measureAngle.xpm"
#include "pdf.xpm"

// Animation buttons (not icons for the stack)
#include "animStop.xpm"
#include "animToLast.xpm"
#include "animStepFwd.xpm"
#include "animStepRwd.xpm"
#include "animToFirst.xpm"
#include "animPlay.xpm"
#include "animPause.xpm"
#include "animPlayRwd.xpm"

// Icons for creating things
#include "createGenericPart.xpm"
#include "getFELink.xpm"
#include "duplicateLink.xpm"
#include "force.xpm"
#include "torque.xpm"
#include "extCtrlSys.xpm"
#include "spider.xpm"
#include "spider_gen.xpm"
#include "spider_gen_rbe2.xpm"
#include "spider_gen_rbe3.xpm"
#include "spider_geom.xpm"
#include "spider_geom_rbe2.xpm"
#include "spider_geom_rbe3.xpm"
#include "splitBeam.xpm"

// Windpower icons
#include "info.xpm"
#include "help.xpm"
#include "windAirEnv.xpm"
#include "treeObjects.xpm"
#include "treeObjectsSel.xpm"
#include "treeResults.xpm"

// Marine icons
#include "beamstringPairDef.xpm"

// Event definition icons
#include "eventDef.xpm"

// Advanced object Info icon
#include "objectInfo.xpm"

// Modelling icons
#include "attach.xpm"
#include "detach.xpm"
#include "pointToPointMove.xpm"
#include "erase.xpm"
#include "eraseStickers.xpm"
#include "forwardSelect.xpm"
#include "backwardSelect.xpm"

// Control pixmaps
#include "ctrlSystem_xpm.xpm"
#include "ctrlRotate.xpm"
#include "ctrlGrid.xpm"
#include "ctrlAddPoint.xpm"
#include "ctrlRemovePoint.xpm"

// Manage icons
#include "RGBSnapshot.xpm"
#include "IVSnapshot.xpm"

// Model solution icons
#include "solve.xpm"
#include "ManageSolve.xpm"
#include "solveAll.xpm"
#include "solveAllEvents.xpm"
#include "solveRosette.xpm"
#include "manageSolveRosette.xpm"
#include "deleteRosetteResults.xpm"
#include "solveStrainCoat.xpm"
#include "manageSolveStrainCoat.xpm"
#include "deleteStrainCoat.xpm"
#include "solveStress.xpm"
#include "manageSolveStress.xpm"
#include "deleteStressResults.xpm"
#include "solveModes.xpm"
#include "manageSolveModes.xpm"
#include "deleteModes.xpm"
#include "solveDutyCycle.xpm"
#include "manageSolveDutyCycle.xpm"
#include "deleteDutyCycle.xpm"
#include "eraseSimuleRes.xpm"
#include "eraseSimuleResEvents.xpm"
#include "refreshRDB.xpm"
#include "eraseAllRes.xpm"
#include "reduceLinks.xpm"
#include "additionalSolverOptions.xpm"
#include "prepareForBatch.xpm"
#include "StopProcessing.xpm"

// Postprocessing icons
#include "animation.xpm"
#include "zoomOut.xpm"
#include "zoomIn.xpm"
#include "curvePlotZoomWindow.xpm"
#include "curvePlotZoomWindowAS.xpm"
#include "modesResList.xpm"
#include "animationControl.xpm"
#include "animationExit.xpm"
#include "animationLoad.xpm"
#include "curve.xpm"
#include "graph.xpm"
#include "graphGroup.xpm"
#include "vtf.xpm"

// Info icons
#include "viewFilter.xpm"
#include "infoList.xpm"
#include "appearance.xpm"
#include "propertyEditor.xpm"
#include "modelManager.xpm"
#include "openMechModeller.xpm"
#include "linkRamSettings.xpm"

// Result file browser
#include "browseRDB_xpm.xpm"

// 3D view icons
#include "zoomAll.xpm"
#include "zoomTo.xpm"
#include "View_XYnZpY.xpm"
#include "View_XYpZpY.xpm"
#include "View_XZnYpZ.xpm"
#include "View_XZpYpZ.xpm"
#include "View_YZnXpZ.xpm"
#include "View_YZpXpZ.xpm"
#include "isometricView.xpm"
#include "paralellView.xpm"
#include "perspectiveView.xpm"
#include "lineView.xpm"
#include "lineViewObj.xpm"
#include "solidView.xpm"
#include "solidViewNoEdge.xpm"
#include "solidViewObj.xpm"
#include "flatColor.xpm"
#include "showTopFaces.xpm"
#include "pan.xpm"
#include "zoom.xpm"
#include "panUp.xpm"
#include "panDown.xpm"
#include "panLeft.xpm"
#include "panRight.xpm"
#include "symbolSize.xpm"

#endif
