// SPDX-FileCopyrightText: 2023 SAP SE
//
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of FEDEM - https://openfedem.org
////////////////////////////////////////////////////////////////////////////////

#ifndef FAP_INIT_H
#define FAP_INIT_H

#include "vpmApp/FapEventManager.H"
#include "vpmApp/vpmAppCmds/FapSelectionCmds.H"
#include "vpmApp/vpmAppCmds/FapAnimationCmds.H"
#include "vpmApp/vpmAppCmds/FapCtrl3DObjCmds.H"
#include "vpmApp/vpmAppCmds/FapAllignCSCmds.H"
#include "vpmApp/vpmAppCmds/FapStrainRosetteCmds.H"
#include "vpmApp/vpmAppCmds/FapDBCreateCmds.H"
#include "vpmApp/vpmAppCmds/FapEditCmds.H"
#include "vpmApp/vpmAppCmds/FapExportCmds.H"
#include "vpmApp/vpmAppCmds/FapFileCmds.H"
#include "vpmApp/vpmAppCmds/FapFunctionCmds.H"
#include "vpmApp/vpmAppCmds/FapGraphCmds.H"
#include "vpmApp/vpmAppCmds/FapHelpCmds.H"
#include "vpmApp/vpmAppCmds/FapMainWinCmds.H"
#include "vpmApp/vpmAppCmds/FapMech3DObjCmds.H"
#include "vpmApp/vpmAppCmds/FapSolveCmds.H"
#include "vpmApp/vpmAppCmds/FapToolsCmds.H"
#include "vpmApp/vpmAppCmds/FapViewCtrlCmds.H"
#include "vpmApp/vpmAppCmds/FapWorkSpaceCmds.H"
#include "vpmApp/vpmAppCmds/FapStrainCoatCmds.H"
#include "vpmApp/vpmAppCmds/FapLinkVisualCmds.H"
#include "vpmApp/vpmAppCmds/FapListViewCmds.H"
#include "vpmApp/vpmAppCmds/FapOutputListCmds.H"

#endif
