// SPDX-FileCopyrightText: 2023 SAP SE
//
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of FEDEM - https://openfedem.org
////////////////////////////////////////////////////////////////////////////////

/*!
  \file FuiQtScaleShiftWidget.C
  \brief Qt-implementation of the scale- and shift-widget for curve data.
  \details Originally this code was generated by Qt's User Interface Compiler
  by reading the file 'scaleShiftWidget.ui'. But later modifications were
  done manually and the ui-file is no longer in use.
  \author Jacob Storen
  \date 8 Oct 2004
*/

#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QGroupBox>
#include <QLabel>

#include "FFuLib/FFuQtComponents/FFuQtIOField.H"
#include "FFuLib/FFuQtComponents/FFuQtToggleButton.H"
#include "vpmUI/vpmUIComponents/vpmUIQtComponents/FuiQtScaleShiftWidget.H"


//! Constructs a FuiQtScaleShiftWidget object as a child of \a parent.
FuiQtScaleShiftWidget::FuiQtScaleShiftWidget(QWidget* parent, const char* name)
  : FFuQtMultUIComponent(parent, name)
{
  this->setSizePolicy(QSizePolicy(QSizePolicy::Ignored,QSizePolicy::Ignored));

  superFrame = new QGroupBox(this);
  superFrame->setSizePolicy(QSizePolicy::Preferred,QSizePolicy::Preferred);
  superFrame->setGeometry(0,0,295,122);
  QVBoxLayout* superFrameLayout = new QVBoxLayout(superFrame);
  superFrameLayout->setAlignment(Qt::AlignTop);
  superFrameLayout->setSpacing(2);

  QHBoxLayout* layout = new QHBoxLayout();
  layout->addWidget(new QLabel("Scale",superFrame));
  layout->addItem(new QSpacerItem(30,10,QSizePolicy::Minimum,QSizePolicy::Preferred));

  FFuQtIOField* qField;
  scaleField = qField = new FFuQtIOField(superFrame);
  scaleField->setInputCheckMode(FFuIOField::DOUBLECHECK);
  scaleField->setAcceptedCB(FFaDynCB1M(FuiQtScaleShiftWidget,this,dblChanged,double));
  layout->addWidget(qField);
  superFrameLayout->addLayout(layout);

  shiftFrame = new QGroupBox(superFrame);
  QVBoxLayout* shiftFrameLayout = new QVBoxLayout(shiftFrame);
  shiftFrameLayout->setAlignment(Qt::AlignTop);
  shiftFrameLayout->setSpacing(2);

  FFuQtToggleButton* qBtn;
  zeroOutBtn = qBtn = new FFuQtToggleButton(shiftFrame);
  zeroOutBtn->setLabel("Shift values to zero out first value");
  shiftFrameLayout->addWidget(qBtn);

  layout = new QHBoxLayout();
  layout->addWidget(new QLabel("Additional shift",shiftFrame));
  layout->addItem(new QSpacerItem(20,10,QSizePolicy::Minimum,QSizePolicy::Preferred));

  shiftField = qField = new FFuQtIOField(shiftFrame);
  shiftField->setInputCheckMode(FFuIOField::DOUBLECHECK);
  shiftField->setAcceptedCB(FFaDynCB1M(FuiQtScaleShiftWidget,this,dblChanged,double));
  layout->addWidget(qField);
  shiftFrameLayout->addLayout(layout);
  superFrameLayout->addWidget(shiftFrame);

  this->resize(QSize(600,480).expandedTo(this->minimumSizeHint()));

  connect(qBtn, SIGNAL(toggled(bool)), this, SLOT(btnToggled(bool)));
}


//! Sets titles for the two frames
void FuiQtScaleShiftWidget::setFrameTitles(const char* main, const char* shift)
{
  superFrame->setTitle(main);
  shiftFrame->setTitle(shift);
}


//! Slot for toggle btn
void FuiQtScaleShiftWidget::btnToggled(bool)
{
  // Invoke the data changed call-back only when the user actually toggles the
  // button - not when selecting an object for which the toggle already was on
  if (!readingDBonly)
    dataChangedCB.invoke();
}

//! Slot for input fields
void FuiQtScaleShiftWidget::dblChanged(double)
{
  dataChangedCB.invoke();
}
